### ISSUE TITLE
Missing surface-dial-ubuntu-gnome.py

### ISSUE THREAD

**Issue by V1d1o7** [runekaagaard/surface-dial-ubuntu-gnome#1]
Running Ubuntu 20.04 on kernel 5.1.15-surface-linux-surface 

After installing python3 (``` sudo apt-get install python3-pip ```) and running the install command ( ```sudo pip3 install -U evdev```) I went ahead and tried to start the script (```surface-dial-ubuntu-gnome.py```) but get the error "sudo: ./surface-dial-ubuntu-gnome.py: command not found". Upon looking in /usr/local/lib/python3.8/dist-packages/evdev i do not see the script nor did doing a search find it either. I tried removing and reinstalling but that did not help either. I ended up downloading the git as a zip and manually moving the file to my home directory and running it as such with no issues. However, is there way to make it a service so that i do not have to keep a terminal window open?

1) Python script (surface-dial-ubuntu-gnome.py) not installed
2) Downloading it manually and running it causes terminal to be open to work, possible to make it a system service instead?

Side note: I am extremely happy I found this as all I want for my dial is to scroll a webpage so I am very pleased it does what little it does! Thank you!!

**Comment by runekaagaard** [comment]
Hi @tdvantine. Great you are finding a use for this little script :) I had to disable bluetooth on my SB2 due to a driver bug so zzz...

Yes you have to download the python script manually. This looks like a great example of how to make a systemd service out of a python script: https://tecadmin.net/setup-autorun-python-script-using-systemd/

You now have commit rights to this repository if you want to update the documentation or add the service file.

Cheers,
Rune

**Comment by V1d1o7** [comment]
I have updated the ReadMe and am currently working on the daemon for systemd. Probably a day or two at most on it. Got a little tangled up with another project in the homelab so sorry for the delay in replying! 

I haven't tried anything yet, but I foresee an issue arising. If we were to start the service at boot then the Dial may not be paired yet and thus the service would end it self due to the error of no dial found. That said, it is still beneficial to have it as a systemd as you can pair the dial still and then restart the daemon and still not have terminal open all the time. Will be interesting to see what happens 🤷🏻‍♂️!

**Comment by runekaagaard** [comment]
Hi @tdvantine. Thats great. Good point with the device not being found. If you get the service working I should be able to make the python script try to reconnect to the device if it's not found instead of chrashing.
