### ISSUE TITLE
Scrolling to fast, other button?

### ISSUE THREAD

**Issue by DgvZsV9kngSt1EZUEd7Z** [runekaagaard/surface-dial-ubuntu-gnome#2]
Hi,
script works, but scrolling is very very fast, even to fast.
One finger on the surface dial an I get 5 to 10 turning events.

Is it possible to sent the turn event to a sh.script instead of rel-wheel?

Can I map the the click-event to another mouse button, 8 for example?

**Comment by runekaagaard** [comment]
On my system it starts out sending really many events, then after a while it drops down in a much slower pace. Don't know why.

It's a very simple script so should be easy to modify.

**Comment by DgvZsV9kngSt1EZUEd7Z** [comment]
It's not easy for me, but I found:
from evdev.ecodes import ... , BTN_SIDE
EV_KEY: [BTN_SIDE],
This works for me.
But the scrolling speed is still to high, nothing changes after waiting for a long time.

**Comment by runekaagaard** [comment]
Cool you found BTN_SIDE! Maybe try introducing a counter so only on in 5 or so events gets triggered?

**Comment by DgvZsV9kngSt1EZUEd7Z** [comment]
I thought about to pause the reading of events for e.g. 100ms.
To count the events would be a better idea, because screwing will be recognised in a correct way.
But my practical knwoledge in programming python is worse.
I didn't get it working till now.

**Comment by DgvZsV9kngSt1EZUEd7Z** [comment]
I solved the speed problem and used the script for http requests:

#!/usr/bin/env python3

import os
import os.path
import sys
import requests

from errno import ENOENT
from evdev import InputDevice, UInput
from evdev.events import InputEvent
from evdev.ecodes import EV_KEY, EV_REL, REL_WHEEL, BTN_MOUSE, REL_HWHEEL, REL_WHEEL_HI_RES, BTN_SIDE
from signal import signal, SIGINT

# Automatically discover the device.
for name in os.listdir('/dev/input'):
    if not name.startswith('event'):
        continue

    dev = InputDevice('/dev/input/' + name)
    if dev.name == "Surface Dial System Multi Axis":
        print("Found surface dial at", dev.path)
        break
else:
    print("Could not find Surface Dial, please pair it and try again.")
    sys.exit(-ENOENT)


def on_exit(s, f):
    dev.ungrab()
    sys.exit(0)


# Take over complete control over the device - no events will be passed to
# other listeners. They are relayed to the virtual stylus created above.
signal(SIGINT, on_exit)
dev.grab()

cap = {
    EV_REL: [REL_WHEEL],
    EV_KEY: [BTN_SIDE],
}


def write(ui, event, _type, code, value):
    ui.write_event(InputEvent(event.sec, event.usec, _type, code, value))
    ui.syn()

eventcountc = 0
eventcountr = 0
roundsc = -10
roundsr = 10
i = 0
try:
    with UInput(cap) as ui:
        for event in dev.read_loop():
          # Äussere IF Schleife zur Eventprüfung
          # Drehen Gegen den Uhrzeigersinn
          if (event.code == 7 and event.type == EV_REL and event.value < 0):
              #  print("Gegen den Uhrzeigersinn")
                eventcountc = eventcountc - 1
               # print (eventcountc)
                if event.value != -1:
                    print("Ungültiger Wert Gegen den Urhzeigersinn", event.value)
                if eventcountc <= roundsc:
                     #write(ui, event, EV_REL, REL_WHEEL, -1)
                #     print("Zeile 65 Eventcountwert erreicht", eventcountc)
                     r = requests.get('http://192.168.2.35/command?code=19083700000200120302210047004E021002210E91000001010101010100000101000000000002&XC_FNC=Send2&ir=08')
                     # Counter ruecksetzen
                     eventcountc = 0
                   #  print("Zeile 68", eventcountc)
                # Zeile 65 wird ausgegeben wenn -10 erreicht wird
                #print("Zeile 70 ", eventcountc
                #elif eventcountc != roundsc:
                  #  print("zeile 71 eventcountc ungleich - Wert ist", eventcountc)
          # Äussere IF Schleife zur Eventprüfung
          # Drehen gegen den Uhrzeigersinn
          elif (event.code == 7 and event.type == EV_REL and event.value > 0):
                #print("TURN CLOCKWISE")
                eventcountr = eventcountr + 1
                if event.value != 1:
                    print("    UNEXPECTED CLOCKWISE VALUE", event.value)
                    if eventcountr >= roundsr:
                        # write(ui, event, EV_REL, REL_WHEEL, -1)
                        #     print("Zeile 65 Eventcountwert erreicht", eventcountc)
                        r = requests.get('http://192.168.2.35/command?code=190837000001002903004D02120226004202260E900001010102010100000000000001010101000001010102010100000000000001010101000001010102&XC_FNC=Send2&ir=08')
                        # Counter ruecksetzen
                        eventcountr = 0
                #write(ui, event, EV_REL, REL_WHEEL, 1)
          # Äussere IF Schleife zur Eventprüfung
          elif (event.code == 256 and event.type == EV_KEY and event.value == 1):
                # print("CLICK DOWN")
                r = requests.get(
                    'http://192.168.2.35/command?code=190837000001004503004E02130225004602250EA2000000000001010101010100000102010100000000000001010101010100000102010100000000000001010101010100000102010100000000000001010101010100000102&XC_FNC=Send2&ir=08')
                # write(ui, event, EV_KEY, BTN_SIDE, 1)
          # Äussere IF Schleife zur Eventprüfung
          elif (event.code == 256 and event.type == EV_KEY and event.value == 0):
                  print("CLICK UP")
                #  write(ui, event, EV_KEY, BTN_SIDE, 0)
finally:
    dev.ungrab()

**Comment by runekaagaard** [comment]
Great you found a evolution! What's happening with the http requests?

**Comment by DgvZsV9kngSt1EZUEd7Z** [comment]
I use the http request to send commands to my homeautomation,
in this case the output is an infrared device and this sends volume control commands to my amplifier.
