### ISSUE TITLE
Surface is  lost, Errno 19, non such device

### ISSUE THREAD

**Issue by DgvZsV9kngSt1EZUEd7Z** [runekaagaard/surface-dial-ubuntu-gnome#3]
Hi,
after a time surface is lost, there is no bluetooth connection,
so I get an error.
Errno 19, non such device

I tried the energy setting
echo "-1" | sudo tee -a /sys/module/usbcore/parameters/autosuspend
and also intel settings
echo -e "options iwlwifi bt_coex_active=0" | sudo tee -a /etc/modprobe.d/iwlwifi.conf

But this wont work, the script and the surface is not working anymore.

**Comment by runekaagaard** [comment]
Yeah, had that too on the SB2. I think it's a driver issue.

**Comment by DgvZsV9kngSt1EZUEd7Z** [comment]
How did you solved the driver issue?

**Comment by runekaagaard** [comment]
I did not. I'm not using bluetooth on my laptop at the moment.

On 8/9/20, DgvZsV9kngSt1EZUEd7Z <notifications@github.com> wrote:
> How did you solved the driver issue?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/runekaagaard/surface-dial-ubuntu-gnome/issues/3#issuecomment-671050064


-- 
Bedste hilsner,

Rune Kaagaard
+45 60601734
